def reverse_each_word(sentence)
  sentence.split10
  puts "Hello there, and how are you?".reverse
end
........................................................................
reverse_each_word(sentence1)209.209..................